const sampleListings = [
  {
    title: "Beachfront Cottage",
    description: "Relax by the beach with beautiful ocean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "Trending",
  },
  {
    title: "Luxury Room",
    description: "Modern room in the city center.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Mumbai",
    country: "India",
    category: "Rooms",
  },
  {
    title: "Paris Apartment",
    description: "Apartment near the Eiffel Tower.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Paris",
    country: "France",
    category: "Iconic Cities",
  },
  {
    title: "Mountain Cabin",
    description: "Peaceful stay in the mountains.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Manali",
    country: "India",
    category: "Mountains",
  },
  {
    title: "Scottish Castle",
    description: "Experience royal living.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=800&q=60",
    },
    price: 4500,
    location: "Edinburgh",
    country: "Scotland",
    category: "Castles",
  },
  {
    title: "Arctic Igloo",
    description: "Watch the Northern Lights.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60",
    },
    price: 5200,
    location: "Lapland",
    country: "Finland",
    category: "Arctic",
  },
  {
    title: "Forest Camping",
    description: "Camping under the stars.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Rishikesh",
    country: "India",
    category: "Camping",
  },
  {
    title: "Organic Farm Stay",
    description: "Experience village life.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Nashik",
    country: "India",
    category: "farms",
  },
  {
    title: "Swiss Chalet",
    description: "Beautiful chalet in the Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=800&q=60",
    },
    price: 2600,
    location: "Zermatt",
    country: "Switzerland",
    category: "Mountains",
  },
  {
    title: "Tokyo Studio",
    description: "Modern apartment in Tokyo.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?auto=format&fit=crop&w=800&q=60",
    },
    price: 2300,
    location: "Tokyo",
    country: "Japan",
    category: "Iconic Cities",
  },
  {
    title: "Dubai Luxury Suite",
    description: "Luxury stay in downtown Dubai.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    location: "Dubai",
    country: "UAE",
    category: "Rooms",
  },
  {
    title: "Bali Pool Villa",
    description: "Villa with private swimming pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Bali",
    country: "Indonesia",
    category: "Trending",
  },
  {
    title: "Himalayan Camp",
    description: "Adventure camping experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Leh",
    country: "India",
    category: "Camping",
  },
  {
    title: "Apple Orchard Farm",
    description: "Stay on a beautiful apple farm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=60",
    },
    price: 1400,
    location: "Shimla",
    country: "India",
    category: "farms",
  },
  {
    title: "Jaipur Heritage Palace",
    description: "Stay in a royal palace hotel.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=800&q=60",
    },
    price: 4800,
    location: "Jaipur",
    country: "India",
    category: "Castles",
  }
  ,
{
  title: "Goa Beach Resort",
  description: "Beachside resort with stunning sunset views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
  },
  price: 2100,
  location: "Goa",
  country: "India",
  category: "Trending",
},
{
  title: "New York Loft",
  description: "Luxury loft in Manhattan.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
  },
  price: 3500,
  location: "New York",
  country: "United States",
  category: "Rooms",
},
{
  title: "London Apartment",
  description: "Apartment near Big Ben.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
  },
  price: 2900,
  location: "London",
  country: "United Kingdom",
  category: "Iconic Cities",
},
{
  title: "Kashmir Cottage",
  description: "Snow-covered mountain cottage.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=800&q=60",
  },
  price: 1800,
  location: "Srinagar",
  country: "India",
  category: "Mountains",
},
{
  title: "French Castle",
  description: "Historic castle surrounded by vineyards.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=800&q=60",
  },
  price: 5200,
  location: "Bordeaux",
  country: "France",
  category: "Castles",
},
{
  title: "Iceland Igloo",
  description: "Glass igloo beneath the aurora.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60",
  },
  price: 6000,
  location: "Reykjavik",
  country: "Iceland",
  category: "Arctic",
},
{
  title: "Jungle Camping",
  description: "Adventure camping in dense forests.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
  },
  price: 850,
  location: "Jim Corbett",
  country: "India",
  category: "Camping",
},
{
  title: "Tea Farm Stay",
  description: "Stay amidst lush tea gardens.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=60",
  },
  price: 1300,
  location: "Munnar",
  country: "India",
  category: "farms",
},
{
  title: "Santorini Villa",
  description: "White villa overlooking the sea.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
  },
  price: 3900,
  location: "Santorini",
  country: "Greece",
  category: "Trending",
},
{
  title: "Delhi Premium Room",
  description: "Comfortable room with modern amenities.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
  },
  price: 1700,
  location: "Delhi",
  country: "India",
  category: "Rooms",
},
{
  title: "Rome Studio",
  description: "Stay close to the Colosseum.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
  },
  price: 2400,
  location: "Rome",
  country: "Italy",
  category: "Iconic Cities",
},
{
  title: "Alpine Lodge",
  description: "Beautiful lodge in the Alps.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
  },
  price: 2600,
  location: "Innsbruck",
  country: "Austria",
  category: "Mountains",
},
{
  title: "German Palace",
  description: "Historic palace with royal interiors.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=800&q=60",
  },
  price: 5500,
  location: "Munich",
  country: "Germany",
  category: "Castles",
},
{
  title: "Snow Cabin",
  description: "Warm cabin surrounded by snow.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=60",
  },
  price: 4300,
  location: "Norway",
  country: "Norway",
  category: "Arctic",
},
{
  title: "Desert Camp",
  description: "Luxury camping under the stars.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
  },
  price: 1400,
  location: "Jaisalmer",
  country: "India",
  category: "Camping",
},
{
  title: "Lavender Farm",
  description: "Peaceful farm stay surrounded by lavender.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=60",
  },
  price: 1500,
  location: "Provence",
  country: "France",
  category: "farms",
},
{
  title: "Maldives Resort",
  description: "Luxury overwater villa.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=800&q=60",
  },
  price: 8000,
  location: "Malé",
  country: "Maldives",
  category: "Trending",
},
{
  title: "Bangalore Studio",
  description: "Affordable studio for professionals.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
  },
  price: 1600,
  location: "Bangalore",
  country: "India",
  category: "Rooms",
},
{
  title: "Sydney Harbour Stay",
  description: "Apartment overlooking the Opera House.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
  },
  price: 3300,
  location: "Sydney",
  country: "Australia",
  category: "Iconic Cities",
},
{
  title: "Himalayan Eco Farm",
  description: "Organic farm stay in the Himalayas.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=60",
  },
  price: 1700,
  location: "Uttarakhand",
  country: "India",
  category: "farms",
}
,
{
  title: "Goa Beach House",
  description: "Beautiful beach house with sea view.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
  },
  price: 2400,
  location: "Goa",
  country: "India",
  category: "Trending",
},
{
  title: "Mumbai Studio",
  description: "Modern studio apartment.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
  },
  price: 1900,
  location: "Mumbai",
  country: "India",
  category: "Rooms",
},
{
  title: "Sydney Apartment",
  description: "Apartment near Opera House.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
  },
  price: 4200,
  location: "Sydney",
  country: "Australia",
  category: "Iconic Cities",
},
{
  title: "Himalayan Cabin",
  description: "Cabin surrounded by snow mountains.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
  },
  price: 2100,
  location: "Leh",
  country: "India",
  category: "Mountains",
},
{
  title: "Scottish Palace",
  description: "Historic palace stay.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98",
  },
  price: 6500,
  location: "Glasgow",
  country: "Scotland",
  category: "Castles",
},
{
  title: "Arctic Snow Camp",
  description: "Stay in the snowy Arctic.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963",
  },
  price: 7200,
  location: "Lapland",
  country: "Finland",
  category: "Arctic",
},
{
  title: "Forest Camping Retreat",
  description: "Camping with bonfire.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
  },
  price: 950,
  location: "Coorg",
  country: "India",
  category: "Camping",
},
{
  title: "Strawberry Farm Stay",
  description: "Farm stay surrounded by strawberries.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
  },
  price: 1350,
  location: "Mahabaleshwar",
  country: "India",
  category: "farms",
},
{
  title: "Glass Dome",
  description: "Luxury transparent dome.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
  },
  price: 3300,
  location: "Iceland",
  country: "Iceland",
  category: "Domes",
},
{
  title: "Luxury Houseboat",
  description: "Houseboat with lake views.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
  },
  price: 2900,
  location: "Alleppey",
  country: "India",
  category: "Boats",
},
{
  title: "Maldives Villa",
  description: "Luxury villa on the beach.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd",
  },
  price: 9500,
  location: "Malé",
  country: "Maldives",
  category: "Trending",
},
{
  title: "Delhi Premium Room",
  description: "Comfortable room in Delhi.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
  },
  price: 1800,
  location: "Delhi",
  country: "India",
  category: "Rooms",
},
{
  title: "Tokyo Skyline Stay",
  description: "Apartment with skyline view.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1480796927426-f609979314bd",
  },
  price: 4100,
  location: "Tokyo",
  country: "Japan",
  category: "Iconic Cities",
},
{
  title: "Swiss Mountain Resort",
  description: "Luxury mountain resort.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000",
  },
  price: 4600,
  location: "Zermatt",
  country: "Switzerland",
  category: "Mountains",
},
{
  title: "Royal Fort Stay",
  description: "Stay inside a heritage fort.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2",
  },
  price: 5200,
  location: "Jaipur",
  country: "India",
  category: "Castles",
},
{
  title: "Polar Cabin",
  description: "Warm cabin in the Arctic.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963",
  },
  price: 6700,
  location: "Norway",
  country: "Norway",
  category: "Arctic",
},
{
  title: "Desert Camp",
  description: "Luxury desert camping.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
  },
  price: 1600,
  location: "Jaisalmer",
  country: "India",
  category: "Camping",
},
{
  title: "Organic Apple Farm",
  description: "Peaceful farm stay.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1464226184884-fa280b87c399",
  },
  price: 1700,
  location: "Shimla",
  country: "India",
  category: "farms",
},
{
  title: "Mountain Dome",
  description: "Glass dome surrounded by mountains.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
  },
  price: 3900,
  location: "Manali",
  country: "India",
  category: "Domes",
},
{
  title: "Venice Boat Stay",
  description: "Stay on a beautiful canal boat.",
  image: {
    filename: "listingimage",
    url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
  },
  price: 4300,
  location: "Venice",
  country: "Italy",
  category: "Boats",
}
  
];

module.exports = { data: sampleListings };